services:
  gaia:
    build:
      context: .
      dockerfile: Dockerfile_gaia
    container_name: gaia
    env_file:
      - ./.env
      - ./.env.gaia
    volumes:
      - ./examples:/app/aworld/examples
      - ./mcp_servers:/app/aworld/mcp_servers
      - ./.data:/app/backend/data
    ports:
      - 8080:8080
    restart: on-failure:3
    deploy:
      resources:
        limits:
          memory: 8G
