services:
  aworldserver-1:
      image: aworldserver:main
      volumes:
        - ./.env:/app/.env
      ports:
        - "9299:9099"
      restart: always
  aworldserver-2:
    image: aworldserver:main
    volumes:
      - ./.env:/app/.env
    ports:
      - "9399:9099"
    restart: always
  aworldserver-3:
    image: aworldserver:main
    volumes:
      - ./.env:/app/.env
    ports:
      - "9499:9099"
    restart: always